import { Platform, StyleSheet } from "react-native";
export const colors = {
  background: "#F6F5F0",
  surface: "#FFFFFF",
  ink: "#203B32",
  muted: "#70796F",
  primary: "#254D3E",
  soft: "#E9EDE3",
  border: "#E2E5DC",
  gold: "#D8B879",
  danger: "#A34D42",
};
export const serif = Platform.select({
  ios: "Georgia",
  android: "serif",
  default: "Georgia",
});
export const ui = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: {
    width: "100%",
    maxWidth: 1040,
    alignSelf: "center",
    padding: 24,
    paddingBottom: 32,
  },
  eyebrow: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2,
  },
  title: { fontFamily: serif, fontSize: 36, color: colors.ink, marginTop: 8 },
  body: { color: colors.muted, fontSize: 14, lineHeight: 22 },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  button: {
    minHeight: 50,
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  buttonText: { color: "#fff", fontSize: 14, fontWeight: "700" },
  iconButton: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  search: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 16,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 14,
    color: colors.ink,
    fontSize: 14,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 14,
    backgroundColor: colors.background,
    color: colors.ink,
    fontSize: 15,
    minHeight: 52,
  },
  chip: {
    paddingHorizontal: 17,
    paddingVertical: 12,
    borderRadius: 24,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 8,
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { color: colors.muted, fontWeight: "600", fontSize: 13 },
  pressed: { opacity: 0.75 },
  error: { color: colors.danger, paddingVertical: 10, fontSize: 14 },
});
